name: Go Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o assinatura-email.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: assinatura-email-windows
          path: assinatura-email.exe